show roles;
use role E2E_SNOW_MLOPS_ROLE;
select top 10 *
from MORTGAGE_LENDING_DEMO_DATA
ORDER BY TS ;

select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='MORTGAGE_LENDING_DEMO_DATA' and TABLE_SCHEMA='MLOPS_SCHEMA';
select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME='MORTGAGE_LENDING_DEMO_DATA' and TABLE_SCHEMA='MLOPS_SCHEMA';

select ABG(LOAN_AMOUNT_000S) from 
    
select COUNTY_NAME,
    LOAN_ID,
    TS,
    LOAN_AMOUNT_000S,
    AVG(LOAN_AMOUNT_000S) OVER (PARTITION BY COUNTY_NAME ORDER BY TO_TIMESTAMP(TS)  ROWS BETWEEN 30 PRECEDING AND CURRENT ROW) AS avg_loan_30day
FROM MORTGAGE_LENDING_DEMO_DATA
where LOAN_ID=150587;

select distinct("LOAN_PURPOSE_NAME") from  MORTGAGE_LENDING_DEMO_DATA;

---- use the EY Data Challenge contect
use database EY_DATA_CHALLENGE;
use schema DATA_SCHEMA;
use role ACCOUNTADMIN;


select top 10 * 
from WATERQUALITY_TRAINING

select top 10 * from LANDSAT_TRAINING;
select current_role();

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION basic_model(
  INPUT_DATA =>
    TABLE(SELECT "SAMPLE DATE", "DISSOLVED REACTIVE PHOSPHORUS" FROM WATERQUALITY_TRAINING WHERE LATITUDE = -25.73411),
  TIMESTAMP_COLNAME => "SAMPLE DATE",
  TARGET_COLNAME => "DISSOLVED REACTIVE PHOSPHORUS",
  LABEL_COLNAME => '');



