show roles;
use role E2E_SNOW_MLOPS_ROLE;
select top 10 *
from MORTGAGE_LENDING_DEMO_DATA
ORDER BY TS ;

select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='MORTGAGE_LENDING_DEMO_DATA' and TABLE_SCHEMA='MLOPS_SCHEMA';
select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME='MORTGAGE_LENDING_DEMO_DATA' and TABLE_SCHEMA='MLOPS_SCHEMA';

select ABG(LOAN_AMOUNT_000S) from 
    
select COUNTY_NAME,
    LOAN_ID,
    TS,
    LOAN_AMOUNT_000S,
    AVG(LOAN_AMOUNT_000S) OVER (PARTITION BY COUNTY_NAME ORDER BY TO_TIMESTAMP(TS)  ROWS BETWEEN 30 PRECEDING AND CURRENT ROW) AS avg_loan_30day
FROM MORTGAGE_LENDING_DEMO_DATA
where LOAN_ID=150587;

select distinct("LOAN_PURPOSE_NAME") from  MORTGAGE_LENDING_DEMO_DATA;

---- use the EY Data Challenge contect
use database EY_DATA_CHALLENGE;
use schema DATA_SCHEMA;
use role ACCOUNTADMIN;


select top 10 * 
from WATERQUALITY_TRAINING

select top 10 * from LANDSAT_TRAINING;
select current_role();

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION basic_model(
  INPUT_DATA =>
    TABLE(SELECT "SAMPLE DATE", "DISSOLVED REACTIVE PHOSPHORUS" FROM WATERQUALITY_TRAINING WHERE LATITUDE = -25.73411),
  TIMESTAMP_COLNAME => "SAMPLE DATE",
  TARGET_COLNAME => "DISSOLVED REACTIVE PHOSPHORUS",
  LABEL_COLNAME => '');





  select LATITUDE,LONGITUDE,count(*) as record_count
  from TERRACLIMATE_TRAINING
  group by all
  order by record_count DESC;

select * from TERRACLIMATE_TRAINING where LATITUDE =-26.98472222	 and LONGITUDE = 26.63227778 order by SAMPLE_DATE DESC; -- Top measurement co-ordinate


  select LATITUDE,LONGITUDE,count(*) as record_count
  from LANDSAT_TRAINING
  group by all
  order by record_count DESC;

  select min (sample_date),max(sample_date) from LANDSAT_TRAINING

  select * from LANDSAT_TRAINING where LATITUDE =-26.98472222	 and LONGITUDE = 26.63227778 order by SAMPLE_DATE DESC; -- Top measurement co-ordinate



# Verify
 SELECT top 10 OBS_TIME,OBS_TIME::TIMESTAMP::DATE as day , LATITUDE, LONGITUDE,RED,GREEN,BLUE  FROM LANDSAT_FETCH  
 
select count(*) from LANDSAT_FETCH;
 SELECT top 10 OBS_TIME::TIMESTAMP::DATE as day ,count(*) FROM LANDSAT_FETCH  
 group by all;



SELECT OBS_TIME, LATITUDE, LONGITUDE,RED,GREEN,BLUE FROM LANDSAT_FETCH LIMIT 5;

select OBS_TIME::TIMESTAMP::DATE as SAMPLE_DATE , LATITUDE, LONGITUDE,
    count(*) as sample_count,
    sum(count(*)) over ( partition by LATITUDE order by LATITUDE) as latitude_count
from LANDSAT_FETCH
group by all

SELECT 
    OBS_TIME::TIMESTAMP::DATE as SAMPLE_DATE,
    LATITUDE,
    LONGITUDE,
    COUNT(*) as sample_count,
    SUM(COUNT(*)) OVER (PARTITION BY LATITUDE, SAMPLE_DATE ORDER BY LATITUDE, SAMPLE_DATE) as latitude_daily_count
FROM LANDSAT_FETCH
GROUP BY ALL

SELECT 
    OBS_TIME::TIMESTAMP::DATE as SAMPLE_DATE,
    LATITUDE,
    LONGITUDE,
    COUNT(*) as sample_count,
    SUM(COUNT(*)) OVER (PARTITION BY LATITUDE, SAMPLE_DATE) as latitude_daily_count
FROM LANDSAT_FETCH
GROUP BY ALL

-Rounding latitude
SELECT top 5
    OBS_TIME::TIMESTAMP::DATE as SAMPLE_DATE,
    ROUND(LATITUDE, 2) as LATITUDE_ROUNDED,  -- adjust precision as needed
    ROUND(LONGITUDE, 2) as LONGITUDE_ROUNDED,
    COUNT(*) as sample_count,
    SUM(COUNT(*)) OVER (PARTITION BY ROUND(LATITUDE, 2), SAMPLE_DATE) as latitude_daily_count
FROM LANDSAT_FETCH
GROUP BY ALL

DESCRIBE TABLE   LANDSAT_FETCH


---
SELECT 
    OBS_TIME::TIMESTAMP::DATE as SAMPLE_DATE,
    ROUND(LATITUDE, 2) as LATITUDE_ROUNDED,
    ROUND(LONGITUDE, 2) as LONGITUDE_ROUNDED,
    COUNT(*) as RECORD_COUNT
FROM LANDSAT_FETCH
GROUP BY 
    OBS_TIME::TIMESTAMP::DATE,
    ROUND(LATITUDE, 2),
    ROUND(LONGITUDE, 2)
ORDER BY 
    SAMPLE_DATE,
    LATITUDE_ROUNDED,
    LONGITUDE_ROUNDED

-- Avg
SELECT 
    OBS_TIME::TIMESTAMP::DATE as SAMPLE_DATE,
    ROUND(LATITUDE, 2) as LATITUDE_ROUNDED,
    ROUND(LONGITUDE, 2) as LONGITUDE_ROUNDED,
    AVG(RED) as RED_AVG,
    AVG(GREEN) as RED_AVG,
    AVG(BLUE) as RED_AVG,
FROM LANDSAT_FETCH
GROUP BY 
    OBS_TIME::TIMESTAMP::DATE,
    ROUND(LATITUDE, 2),
    ROUND(LONGITUDE, 2)
ORDER BY 
    SAMPLE_DATE,
    LATITUDE_ROUNDED,
    LONGITUDE_ROUNDED

    


select OBS_TIME as SAMPLE_DATE,ROUND(LATITUDE, 2) as LATITUDE_ROUNDED ,
    ROUND(LONGITUDE, 2) as LONGITUDE_ROUNDED, 
    RED,GREEN,BLUE 
from LANDSAT_FETCH
where  ROUND(LATITUDE, 2)=-27.06
and  ROUND(LONGITUDE, 2) =26.56
and OBS_TIME::TIMESTAMP::DATE ='2011-09-04'

select top 10 * from LANDSAT_TRAINING;
SELECT * from LANDSAT_TRAINING where SAMPLE_DATE in (select OBS_TIME::TIMESTAMP::DATE from LANDSAT_FETCH)
and  LATITUDE in () =-27.06 and LONGITUDE=	26.56;


select Top 10  LT.SAMPLE_DATE, 
ROUND(LT.LATITUDE, 2) as TRAIN_LAT ,
ROUND(LT.LONGITUDE, 2) as TRAIN_LON, 
ROUND(LF.LATITUDE, 2) FETCH_LAT ,
ROUND(LF.LONGITUDE, 2) as FETCH_LON, 
LT.GREEN as TRAIN_GREEN , LF.GREEN as FETCH_GREEN,
LF.RED as FETCH_RED,
LF.BLUE as FETCH_BLUE
from LANDSAT_TRAINING LT
inner join LANDSAT_FETCH LF on LT.SAMPLE_DATE = LF.OBS_TIME::TIMESTAMP::DATE
and  ROUND(LT.LATITUDE, 2) =ROUND(LF.LATITUDE, 2)
and  ROUND(LT.LONGITUDE, 2) =ROUND(LF.LONGITUDE, 2)    
